### ISSUE TITLE
ExceptionModel#toString returns values for params with wrong toString-Method

### ISSUE THREAD

**Issue by hlober** [imamchishty/exception-core#2]
Hi,

in your ExceptionModel#toString you call toString for your Map<String, Object> parameter map.
So when e.g. ExceptionController#log is called our request params String get returned from Object#toString.

Please change this behaviour to calling the real toString-Method (if available).

Thanks.

Regards,

Holger

**Comment by imamchishty** [comment]
Hi Holger,

You're referring to:

\"params\":" + params

Is that the issue for you?

**Comment by hlober** [comment]
Yes, that´s the issue. The map is String, Object and there´s always toString from Object.class called and not from String or any other class.

**Comment by hlober** [comment]
Have you checked this yet? :)

**Comment by imamchishty** [comment]
Hey!

The SomeObject class doesn't implement toString so the result looks like:


*"params":{someObject=com.shedhack.exception.core.ExceptionModelTest$SomeObject@4c98385c}*
If toString was implemented we would see:


*"params":{someObject={"SomeObject":{"key":"hello", "value":"42",
"child":{"SomeChildObject":{"name":"John"}}}}}*

Do you not have access to the nested object?

**Comment by imamchishty** [comment]
Even if we do something like (in ExceptionModel):

ReflectionToStringBuilder.toString(this);

We won't still have the desired result:

**params={someObject=com.shedhack.exception.core.ExceptionModelTest$SomeObject@7dc5e7b4}**

**Comment by imamchishty** [comment]
Options available:

Implement toString OR Convert to json, e.g. using Gson:

**{"exceptionId":"2bced9a5-5aa8-4836-bb26-cfaa5bb42a2c","httpStatusDescription":"desc","path":"/api/v1/resource","sessionId":"abcd1234","helpLink":"http://help","message":"Something went wrong here is the exception Id d99306bc-4b04-4a34-b7e7-f5554383f570","exceptionClass":"java.lang.IllegalArgumentException","applicationName":"foo","metadata":"exception-core-model","httpStatusCode":500,#**"params":{"someObject":{"key":"key","value":42,"child":{"name":"John"}}}**,"businessCodes":{},"context":{},"exceptionChain":[{"correlationId":"d99306bc-4b04-4a34-b7e7-f5554383f570","message":"Something went wrong here is the exception Id d99306bc-4b04-4a34-b7e7-f5554383f570"}],"dateTime":"Jun 19, 2017 10:30:40 AM"}**

**Comment by hlober** [comment]
I get e.g. following output:

{"dateTime":Tue Feb 14 15:47:47 CET 2017, "groupId":"null", "requestId":"null", "exceptionId":"2d502650-0286-4a31-91ec-6a6597d82a10", "httpStatusDescription":"Internal Server Error", "path":"/api/visitorrecognizing/recognizeByVisitor", "sessionId":"CA61533C46DE2735275F0BBE81117E72", "helpLink":"", "message":"java.io.IOException: Datenübergabe unterbrochen (broken pipe)", "exceptionClass":"org.apache.catalina.connector.ClientAbortException", "applicationName":"ecom-ws-visitor-recognizing", "metadata":"exception-core-model", "httpStatusCode":"500", "params":
{fingerprint=[Ljava.lang.String;@7fdc3201, companyId=[Ljava.lang.String;@3d719169, visitorId=[Ljava.lang.String;@1368fdb2}
, "businessCodes":{}, "context":
{thread-name=http-nio-auto-1-exec-11}
, "exceptionChain":[ExceptionChainModel
{correlationId='null', message='java.io.IOException: Datenübergabe unterbrochen (broken pipe)'}
, ExceptionChainModel
{correlationId='null', message='Datenübergabe unterbrochen (broken pipe)'}
]}

fingerprint is following class:
`
public class Fingerprint extends AbstractSimpleValueObject<String> {

    private static final String SEPARATOR = "_";

    private String rawValue;
    private int version;

    /**
     * <h1>Konstruktor basierend auf einen Fingerprint-Value mit eincodierter Versionsangabe in der Form "«version»«separator»«value»"</h1>
     *
     * @param value der Fingerprint Wert inkl. Versionsangabe
     */
    public Fingerprint( String value ) {
        super( value );

        if( value.length() < 6 ) {
            throw new IllegalArgumentException( "Incorrect fingerprint-value (to short)!" );
        }

        String[] parts = value.split( SEPARATOR );
        if( parts.length != 2 ) {
            throw new IllegalArgumentException( "Incorrect fingerprint-value (malformed)!" );
        }

        try {
            this.version = Integer.parseInt( parts[0] );
        } catch( NumberFormatException ex ) {
            throw new IllegalArgumentException( "Incorrect fingerprint-value (version must be a integer)!" );
        }

        this.rawValue = parts[1];
    }

    public String getRawValue() {
        return this.rawValue;
    }

    public int getVersion() {
        return this.version;
    }

    @Override public String toString() {
        return this.rawValue;
    }
}
`

Fingerprint#toString seems not to be called for my class

**Comment by imamchishty** [comment]
Are you also using spring-boost or other dependencies?

I think the best fix for you is the json output which I can push and release.

**Comment by hlober** [comment]
Yes, I´m using spring boot and a lot of other deps :)

Okay push and release and I will try.

Thank you very much

**Comment by imamchishty** [comment]
I'll only release exception-core now and wait for your feedback.

2.1.1 will be available in bintray in the next few minutes but takes up to 6 hours to be in maven central.

**Comment by imamchishty** [comment]
Fix is now in [bintray](https://bintray.com/imamchishty/maven/exception-core/2.1.1#)

I've synced with [Maven Central](http://search.maven.org/#artifactdetails%7Ccom.shedhack.exception%7Cexception-core%7C2.1.0%7C) but it'll take a few hours to refresh.

**Comment by hlober** [comment]
HI. I´ve testet and it works fine with json.

The only thing i recognized was that when calling /exceptions for webservice i always get empty result.
/requests and /health is fine.

Any idea?

I have following deps:

        `<dependency>
            <groupId>com.shedhack.thread</groupId>
            <artifactId>thread-context-handler</artifactId>
            <version>${shedhack.thread-context-aspect.version}</version>
        </dependency>

        <dependency>
            <groupId>com.shedhack.exception</groupId>
            <artifactId>exception-core</artifactId>
            <version>${shedhack.exception-core.version}</version>
        </dependency>

        <dependency>
            <groupId>com.shedhack.trace</groupId>
            <artifactId>trace-request-api</artifactId>
            <version>${shedhack.trace-request-api.version}</version>
        </dependency>

        <dependency>
            <groupId>com.shedhack.trace</groupId>
            <artifactId>trace-request-filter</artifactId>
            <version>${shedhack.trace-request-filter.version}</version>
        </dependency>

        <dependency>
            <groupId>com.shedhack.exception</groupId>
            <artifactId>exception-controller-spring</artifactId>
            <version>${shedhack.exception-controller-spring.version}</version>
        </dependency>

        <dependency>
            <groupId>com.shedhack.thread</groupId>
            <artifactId>thread-context-handler</artifactId>
            <version>${shedhack.thread-context-handler.version}</version>
        </dependency>

        <dependency>
            <groupId>com.shedhack.spring</groupId>
            <artifactId>spring-actuator</artifactId>
            <version>${shedhack.spring-actuator.version}</version>
        </dependency>`

I´m using following versions:
<shedhack.trace-request-api.version>2.1.0</shedhack.trace-request-api.version>
        <shedhack.trace-request-filter.version>2.1.0</shedhack.trace-request-filter.version>
        <shedhack.exception-controller-spring.version>2.1.0</shedhack.exception-controller-spring.version>
        <shedhack.exception-core.version>2.1.1</shedhack.exception-core.version>
        <shedhack.thread-context-handler.version>2.1.0</shedhack.thread-context-handler.version>
        <shedhack.thread-context-aspect.version>2.1.0</shedhack.thread-context-aspect.version>
        <shedhack.spring-actuator.version>2.1.0</shedhack.spring-actuator.version>

**Comment by imamchishty** [comment]
I think it's due to version mix-match.

I'll release all of the other components to use the new version of
exception-core. See this hierarchy:

https://github.com/imamchishty/artifact-versions

I'm tempted to put them all to 2.2.0 and get them consistent.

**Comment by imamchishty** [comment]
Which version of spring-boot are you currently on?

**Comment by hlober** [comment]
1.5.1.RELEASE

Cloud: Brixton.SR7

**Comment by imamchishty** [comment]
OK changes have been made most of the projects and they're all at 2.2.0.

I have updated:
`version of spring-boot used is 1.5.4.RELEASE.`
`version of spring-cloud-dependencies is Dalston.SR1.`

https://github.com/imamchishty/artifact-versions shows the lastest versions in maven central, as with before it may take a few hours to refresh. 

As for the /exceptions endpoint not working I have tested locally and seems to be OK, as does /requests. For an example see this config `https://github.com/imamchishty/spring-actuator/blob/master/src/test/java/spring/Application.java`.

**Comment by imamchishty** [comment]
Good to close this issue?

**Comment by hlober** [comment]
Yeah :)
works fine, I had to add

@Autowired
    private ActuatorExceptionInterceptor actuatorExceptionInterceptor;

    @Bean
    public List<ExceptionInterceptor> exceptionInterceptors() {
        return Arrays.asList( actuatorExceptionInterceptor );
    }

In my Config class to make it work.

Thank you very much

Regards,
Holger

**Comment by imamchishty** [comment]
Glad it works!

Cheers
